package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZhuhu<M extends BaseZhuhu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setH1(java.lang.String H1) {
		set("H1", H1);
		return (M)this;
	}
	
	public java.lang.String getH1() {
		return getStr("H1");
	}

	public M setH2(java.lang.String H2) {
		set("H2", H2);
		return (M)this;
	}
	
	public java.lang.String getH2() {
		return getStr("H2");
	}

	public M setH31(java.lang.String h31) {
		set("H3_1", h31);
		return (M)this;
	}
	
	public java.lang.String getH31() {
		return getStr("H3_1");
	}

	public M setH32(java.lang.String h32) {
		set("H3_2", h32);
		return (M)this;
	}
	
	public java.lang.String getH32() {
		return getStr("H3_2");
	}

	public M setH41(java.lang.String h41) {
		set("H4_1", h41);
		return (M)this;
	}
	
	public java.lang.String getH41() {
		return getStr("H4_1");
	}

	public M setH42(java.lang.String h42) {
		set("H4_2", h42);
		return (M)this;
	}
	
	public java.lang.String getH42() {
		return getStr("H4_2");
	}

	public M setH43(java.lang.String h43) {
		set("H4_3", h43);
		return (M)this;
	}
	
	public java.lang.String getH43() {
		return getStr("H4_3");
	}

	public M setH44(java.lang.String h44) {
		set("H4_4", h44);
		return (M)this;
	}
	
	public java.lang.String getH44() {
		return getStr("H4_4");
	}

	public M setH5(java.lang.String H5) {
		set("H5", H5);
		return (M)this;
	}
	
	public java.lang.String getH5() {
		return getStr("H5");
	}

	public M setH6(java.lang.String H6) {
		set("H6", H6);
		return (M)this;
	}
	
	public java.lang.String getH6() {
		return getStr("H6");
	}

	public M setBdcode(java.lang.String bdcode) {
		set("bdcode", bdcode);
		return (M)this;
	}
	
	public java.lang.String getBdcode() {
		return getStr("bdcode");
	}

}
